CREATE SEQUENCE ID_VENTA START WITH 100
CREATE SEQUENCE ID_USUARIO START WITH 100
CREATE SEQUENCE ID_PERFIL START WITH 100
CREATE SEQUENCE ID_PERFIL_USUARIO START WITH 100
CREATE SEQUENCE ID_MENU WITH 100
CREATE SEQUENCE ID_PERFIL_MENU START WITH 100
CREATE SEQUENCE ID_ESTABLECIMIENTO START WITH 100
CREATE SEQUENCE ID_SUCURSAL START WITH 100
CREATE SEQUENCE ID_BODEGA START WITH 100
CREATE SEQUENCE ID_CATALOGO START WITH 100
CREATE SEQUENCE ID_PRODUCTO START WITH 100
CREATE TABLE USUARIO("ID" INTEGER not null primary key, "NOMBRE" VARCHAR(50), "USUARIO" VARCHAR(100), "CLAVE" VARCHAR(50))
CREATE TABLE PERFIL("ID" INTEGER not null primary key, "NOMBRE" VARCHAR(50), "DESCRIPCION" VARCHAR(100))
CREATE TABLE PERFILXUSUARIO("ID" INTEGER not null primary key, "ID_USUARIO" INTEGER references USUARIO(ID), "ID_PERFIL" INTEGER references PERFIL(ID), "ESTADO" BOOLEAN)
CREATE TABLE MENU("ID" INTEGER not null primary key, "NOMBRE" VARCHAR(50), "URL" VARCHAR(100))
CREATE TABLE PERFILXMENU("ID" INTEGER not null primary key, "ID_MENU" INTEGER references MENU(ID),"ID_PERFIL" INTEGER references PERFIL(ID),"ESTADO" BOOLEAN )
CREATE TABLE ESTABLECIMIENTO("ID" INTEGER not null primary key, "NOMBRE" VARCHAR(100), "RUC" VARCHAR(100))
CREATE TABLE ESTABLECIMIENTOXUSUARIO("ID" INTEGER not null primary key, "ID_ESTABLECIMIENTO" INTEGER references ESTABLECIMIENTO(ID),"ID_USUARIO" INTEGER references USUARIO(ID),"ESTADO" BOOLEAN )
CREATE TABLE SUCURSAL("ID" INTEGER not null primary key,"CODIGO" VARCHAR(10), "NOMBRE" VARCHAR(100), "SUCURSAL" VARCHAR(100), "DIRECCION" VARCHAR(100), "ID_ESTABLECIMIENTO" INTEGER references ESTABLECIMIENTO(ID))
CREATE TABLE BODEGA("ID" INTEGER not null primary key,"CODIGO" VARCHAR(10), "NOMBRE" VARCHAR(50), "DIRECCION" VARCHAR(100), "ID_SUCURSAL" INTEGER references SUCURSAL(ID))
CREATE TABLE CATALOGO("ID" INTEGER not null primary key,"CODIGO" VARCHAR(10),"VALOR" VARCHAR(100), "DESCRIPCION" VARCHAR(500), "ESTADO" boolean)
CREATE TABLE PRODUCTO("ID" INTEGER not null primary key,"CODIGO" VARCHAR(10),"MARCA" VARCHAR(100), "NOMBRE" VARCHAR(1000),"DESCRIPCION" VARCHAR(2000), "IMAGEN_URL"  VARCHAR(500) , "CANTIDAD" INTEGER, "PRECIO_UNITARIO" DOUBLE,"ID_CATALOGO_TIPO" INTEGER references CATALOGO(ID), "ID_BODEGA" INTEGER references BODEGA(ID), "ESTADO" boolean)
CREATE TABLE PERSON("ID" INTEGER not null primary key, "NAME" VARCHAR(50), "DESCRIPTION" VARCHAR(100), "IMAGEURL" VARCHAR(500))
CREATE TABLE VENTA("ID" INTEGER not null primary key, "ID_PRODUCTO" INTEGER references PRODUCTO(ID), "ID_USUARIO" INTEGER references USUARIO(ID), "CANTIDAD" INTEGER, "VALOR_TOTAL" DOUBLE, "ESTADO" BOOLEAN )